import { DetailsPageTemplate } from "@/components/templates/details-page";
import { SectionCard } from "@/components/ds/page-header";
import { StatusChip } from "@/components/ds/status-chip";
import { Button } from "@/components/ui/button";
import { Progress } from "@/components/ui/progress";
import { AIValidationService } from "../services/ai-validation.service";
import { AIValidationRecord } from "../types/ai-validation.types";
import { useEffect, useState } from "react";
import { useRouterState } from "@tanstack/react-router";
import { ShieldAlert, ShieldCheck } from "lucide-react";

export function ValidationDetailsPage() {
  const [record, setRecord] = useState<AIValidationRecord | null>(null);
  const routerState = useRouterState();
  const id = routerState.location.pathname.split("/").pop() || "";

  useEffect(() => {
    AIValidationService.getValidationById(id).then((r) => setRecord(r || null));
  }, [id]);

  if (!record) return null; // In real app, add loading state

  return (
    <DetailsPageTemplate
      title={`Validation Report: ${record.submissionId}`}
      description={`${record.title} · ${record.team} · ${record.competition}`}
      crumbs={[
        { label: "AI & Automation" },
        { label: "AI Validation", to: "/ai-validation" },
        { label: "Report" },
      ]}
      meta={
        <>
          <StatusChip status={record.status} />
          <span className="text-xs text-muted-foreground">Scanned {record.createdDate}</span>
        </>
      }
      actions={
        <>
          <Button variant="outline">Reject Submission</Button>
          <Button>Approve Submission</Button>
        </>
      }
      metrics={[
        { label: "Plagiarism Match", value: `${record.plagiarismScore}%` },
        { label: "AI Confidence", value: `${record.aiContentScore}%` },
        { label: "Code Quality", value: `${record.codeQuality}/100` },
        { label: "Duplicate Risk", value: `${record.duplicateScore}%` },
      ]}
      overview={
        <>
          <SectionCard title="Validation Summary" description="Overall integrity assessment">
            <div className="flex items-start gap-4 mb-6">
              {record.status === "flagged" ? (
                <ShieldAlert className="w-12 h-12 text-warning" />
              ) : (
                <ShieldCheck className="w-12 h-12 text-success" />
              )}
              <div>
                <h3 className="text-lg font-medium">
                  {record.status === "flagged" ? "Action Required" : "Validation Passed"}
                </h3>
                <p className="text-sm text-muted-foreground">
                  This submission has been automatically processed by the AI validation engine.{" "}
                  {record.status === "flagged"
                    ? "Multiple risk indicators crossed the acceptable threshold."
                    : "No significant risk indicators were found."}
                </p>
              </div>
            </div>
          </SectionCard>

          <SectionCard
            title="Detailed Analysis"
            description="Breakdown of AI checks"
            padded={false}
          >
            <ul className="divide-y divide-border">
              {[
                {
                  label: "Text Plagiarism",
                  score: record.plagiarismScore,
                  threshold: 30,
                  notes: "Checked against public repositories and past submissions.",
                },
                {
                  label: "AI Generated Content",
                  score: record.aiContentScore,
                  threshold: 50,
                  notes: "Probability of text being generated by LLMs.",
                },
                {
                  label: "Duplicate Detection",
                  score: record.duplicateScore,
                  threshold: 10,
                  notes: "Similarity to concurrent submissions in this event.",
                },
              ].map((c) => (
                <li key={c.label} className="px-5 py-4">
                  <div className="grid grid-cols-[minmax(0,1fr)_auto] items-center gap-3">
                    <p className="truncate text-sm font-medium">{c.label}</p>
                    <span className="shrink-0 text-sm tabular-nums">{c.score}% Match</span>
                  </div>
                  <Progress
                    value={c.score}
                    className={`mt-2 h-1.5 ${c.score > c.threshold ? "bg-warning/20 [&>div]:bg-warning" : "bg-success/20 [&>div]:bg-success"}`}
                  />
                  <p className="mt-2 text-xs text-muted-foreground">{c.notes}</p>
                </li>
              ))}
            </ul>
          </SectionCard>
        </>
      }
    />
  );
}
