import { ListPageTemplate } from "@/components/templates/list-page";
import type { Column } from "@/components/ds/data-table";
import { useManagerEvents } from "../hooks/manager.api";
import { ApiEvent } from "@/modules/events/services/events.api";

export function ManagerRevenuePage() {
  const { data: events = [], isLoading } = useManagerEvents();

  const columns: Column<ApiEvent>[] = [
    {
      key: "name",
      header: "Event",
      sortable: true,
      render: (row) => <span className="font-medium">{row.name}</span>,
    },
    {
      key: "revenue",
      header: "Revenue",
      render: (row) => (
        <span className="font-medium text-green-600">
          {row.currency.toUpperCase()} {(row.revenue || 0).toFixed(2)}
        </span>
      ),
    }
  ];

  return (
    <ListPageTemplate<ApiEvent>
      title="Event Revenue"
      description="View revenue generated by your events."
      crumbs={[{ label: "Manager" }, { label: "Event Revenue" }]}
      columns={columns}
      rows={events}
      loading={isLoading}
      searchKeys={["name"]}
    />
  );
}
