/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuditLogsRouteImport } from './routes/audit-logs'
import { Route as EvaluationsRouteImport } from './routes/evaluations'
import { Route as JudgesRouteImport } from './routes/judges'
import { Route as MentorsRouteImport } from './routes/mentors'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as OrganizationsRouteImport } from './routes/organizations'
import { Route as RecruitmentRouteImport } from './routes/recruitment'
import { Route as RegistrationsRouteImport } from './routes/registrations'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RolesRouteImport } from './routes/roles'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SponsorsRouteImport } from './routes/sponsors'
import { Route as SubscriptionsRouteImport } from './routes/subscriptions'
import { Route as UsersRouteImport } from './routes/users'
import { Route as VolunteersRouteImport } from './routes/volunteers'
import { Route as AnalyticsParticipationRouteImport } from './routes/analytics.participation'
import { Route as AnalyticsRevenueRouteImport } from './routes/analytics.revenue'
import { Route as CertificatesIndexRouteImport } from './routes/certificates.index'
import { Route as CertificatesIdRouteImport } from './routes/certificates.$id'
import { Route as CompetitionsIndexRouteImport } from './routes/competitions.index'
import { Route as CompetitionsIdRouteImport } from './routes/competitions.$id'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as EventsIdRouteImport } from './routes/events.$id'
import { Route as EventsNewRouteImport } from './routes/events.new'
import { Route as EventsScheduleRouteImport } from './routes/events.schedule'
import { Route as SubmissionsIndexRouteImport } from './routes/submissions.index'
import { Route as SubmissionsIdRouteImport } from './routes/submissions.$id'
import { Route as TeamsIndexRouteImport } from './routes/teams.index'
import { Route as TeamsIdRouteImport } from './routes/teams.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogsRoute = AuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluationsRoute = EvaluationsRouteImport.update({
  id: '/evaluations',
  path: '/evaluations',
  getParentRoute: () => rootRouteImport,
} as any)
const JudgesRoute = JudgesRouteImport.update({
  id: '/judges',
  path: '/judges',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorsRoute = MentorsRouteImport.update({
  id: '/mentors',
  path: '/mentors',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsRoute = OrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruitmentRoute = RecruitmentRouteImport.update({
  id: '/recruitment',
  path: '/recruitment',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrationsRoute = RegistrationsRouteImport.update({
  id: '/registrations',
  path: '/registrations',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesRoute = RolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorsRoute = SponsorsRouteImport.update({
  id: '/sponsors',
  path: '/sponsors',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionsRoute = SubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const VolunteersRoute = VolunteersRouteImport.update({
  id: '/volunteers',
  path: '/volunteers',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsParticipationRoute = AnalyticsParticipationRouteImport.update({
  id: '/analytics/participation',
  path: '/analytics/participation',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRevenueRoute = AnalyticsRevenueRouteImport.update({
  id: '/analytics/revenue',
  path: '/analytics/revenue',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatesIndexRoute = CertificatesIndexRouteImport.update({
  id: '/certificates/',
  path: '/certificates/',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatesIdRoute = CertificatesIdRouteImport.update({
  id: '/certificates/$id',
  path: '/certificates/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitionsIndexRoute = CompetitionsIndexRouteImport.update({
  id: '/competitions/',
  path: '/competitions/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitionsIdRoute = CompetitionsIdRouteImport.update({
  id: '/competitions/$id',
  path: '/competitions/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIdRoute = EventsIdRouteImport.update({
  id: '/events/$id',
  path: '/events/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsNewRoute = EventsNewRouteImport.update({
  id: '/events/new',
  path: '/events/new',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsScheduleRoute = EventsScheduleRouteImport.update({
  id: '/events/schedule',
  path: '/events/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmissionsIndexRoute = SubmissionsIndexRouteImport.update({
  id: '/submissions/',
  path: '/submissions/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmissionsIdRoute = SubmissionsIdRouteImport.update({
  id: '/submissions/$id',
  path: '/submissions/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsIndexRoute = TeamsIndexRouteImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsIdRoute = TeamsIdRouteImport.update({
  id: '/teams/$id',
  path: '/teams/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit-logs': typeof AuditLogsRoute
  '/evaluations': typeof EvaluationsRoute
  '/judges': typeof JudgesRoute
  '/mentors': typeof MentorsRoute
  '/notifications': typeof NotificationsRoute
  '/organizations': typeof OrganizationsRoute
  '/recruitment': typeof RecruitmentRoute
  '/registrations': typeof RegistrationsRoute
  '/reports': typeof ReportsRoute
  '/roles': typeof RolesRoute
  '/settings': typeof SettingsRoute
  '/sponsors': typeof SponsorsRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/users': typeof UsersRoute
  '/volunteers': typeof VolunteersRoute
  '/analytics/participation': typeof AnalyticsParticipationRoute
  '/analytics/revenue': typeof AnalyticsRevenueRoute
  '/certificates/$id': typeof CertificatesIdRoute
  '/competitions/$id': typeof CompetitionsIdRoute
  '/events/$id': typeof EventsIdRoute
  '/events/new': typeof EventsNewRoute
  '/events/schedule': typeof EventsScheduleRoute
  '/submissions/$id': typeof SubmissionsIdRoute
  '/teams/$id': typeof TeamsIdRoute
  '/certificates/': typeof CertificatesIndexRoute
  '/competitions/': typeof CompetitionsIndexRoute
  '/events/': typeof EventsIndexRoute
  '/submissions/': typeof SubmissionsIndexRoute
  '/teams/': typeof TeamsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit-logs': typeof AuditLogsRoute
  '/evaluations': typeof EvaluationsRoute
  '/judges': typeof JudgesRoute
  '/mentors': typeof MentorsRoute
  '/notifications': typeof NotificationsRoute
  '/organizations': typeof OrganizationsRoute
  '/recruitment': typeof RecruitmentRoute
  '/registrations': typeof RegistrationsRoute
  '/reports': typeof ReportsRoute
  '/roles': typeof RolesRoute
  '/settings': typeof SettingsRoute
  '/sponsors': typeof SponsorsRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/users': typeof UsersRoute
  '/volunteers': typeof VolunteersRoute
  '/analytics/participation': typeof AnalyticsParticipationRoute
  '/analytics/revenue': typeof AnalyticsRevenueRoute
  '/certificates/$id': typeof CertificatesIdRoute
  '/competitions/$id': typeof CompetitionsIdRoute
  '/events/$id': typeof EventsIdRoute
  '/events/new': typeof EventsNewRoute
  '/events/schedule': typeof EventsScheduleRoute
  '/submissions/$id': typeof SubmissionsIdRoute
  '/teams/$id': typeof TeamsIdRoute
  '/certificates': typeof CertificatesIndexRoute
  '/competitions': typeof CompetitionsIndexRoute
  '/events': typeof EventsIndexRoute
  '/submissions': typeof SubmissionsIndexRoute
  '/teams': typeof TeamsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit-logs': typeof AuditLogsRoute
  '/evaluations': typeof EvaluationsRoute
  '/judges': typeof JudgesRoute
  '/mentors': typeof MentorsRoute
  '/notifications': typeof NotificationsRoute
  '/organizations': typeof OrganizationsRoute
  '/recruitment': typeof RecruitmentRoute
  '/registrations': typeof RegistrationsRoute
  '/reports': typeof ReportsRoute
  '/roles': typeof RolesRoute
  '/settings': typeof SettingsRoute
  '/sponsors': typeof SponsorsRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/users': typeof UsersRoute
  '/volunteers': typeof VolunteersRoute
  '/analytics/participation': typeof AnalyticsParticipationRoute
  '/analytics/revenue': typeof AnalyticsRevenueRoute
  '/certificates/$id': typeof CertificatesIdRoute
  '/competitions/$id': typeof CompetitionsIdRoute
  '/events/$id': typeof EventsIdRoute
  '/events/new': typeof EventsNewRoute
  '/events/schedule': typeof EventsScheduleRoute
  '/submissions/$id': typeof SubmissionsIdRoute
  '/teams/$id': typeof TeamsIdRoute
  '/certificates/': typeof CertificatesIndexRoute
  '/competitions/': typeof CompetitionsIndexRoute
  '/events/': typeof EventsIndexRoute
  '/submissions/': typeof SubmissionsIndexRoute
  '/teams/': typeof TeamsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit-logs'
    | '/evaluations'
    | '/judges'
    | '/mentors'
    | '/notifications'
    | '/organizations'
    | '/recruitment'
    | '/registrations'
    | '/reports'
    | '/roles'
    | '/settings'
    | '/sponsors'
    | '/subscriptions'
    | '/users'
    | '/volunteers'
    | '/analytics/participation'
    | '/analytics/revenue'
    | '/certificates/$id'
    | '/competitions/$id'
    | '/events/$id'
    | '/events/new'
    | '/events/schedule'
    | '/submissions/$id'
    | '/teams/$id'
    | '/certificates/'
    | '/competitions/'
    | '/events/'
    | '/submissions/'
    | '/teams/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit-logs'
    | '/evaluations'
    | '/judges'
    | '/mentors'
    | '/notifications'
    | '/organizations'
    | '/recruitment'
    | '/registrations'
    | '/reports'
    | '/roles'
    | '/settings'
    | '/sponsors'
    | '/subscriptions'
    | '/users'
    | '/volunteers'
    | '/analytics/participation'
    | '/analytics/revenue'
    | '/certificates/$id'
    | '/competitions/$id'
    | '/events/$id'
    | '/events/new'
    | '/events/schedule'
    | '/submissions/$id'
    | '/teams/$id'
    | '/certificates'
    | '/competitions'
    | '/events'
    | '/submissions'
    | '/teams'
  id:
    | '__root__'
    | '/'
    | '/audit-logs'
    | '/evaluations'
    | '/judges'
    | '/mentors'
    | '/notifications'
    | '/organizations'
    | '/recruitment'
    | '/registrations'
    | '/reports'
    | '/roles'
    | '/settings'
    | '/sponsors'
    | '/subscriptions'
    | '/users'
    | '/volunteers'
    | '/analytics/participation'
    | '/analytics/revenue'
    | '/certificates/$id'
    | '/competitions/$id'
    | '/events/$id'
    | '/events/new'
    | '/events/schedule'
    | '/submissions/$id'
    | '/teams/$id'
    | '/certificates/'
    | '/competitions/'
    | '/events/'
    | '/submissions/'
    | '/teams/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditLogsRoute: typeof AuditLogsRoute
  EvaluationsRoute: typeof EvaluationsRoute
  JudgesRoute: typeof JudgesRoute
  MentorsRoute: typeof MentorsRoute
  NotificationsRoute: typeof NotificationsRoute
  OrganizationsRoute: typeof OrganizationsRoute
  RecruitmentRoute: typeof RecruitmentRoute
  RegistrationsRoute: typeof RegistrationsRoute
  ReportsRoute: typeof ReportsRoute
  RolesRoute: typeof RolesRoute
  SettingsRoute: typeof SettingsRoute
  SponsorsRoute: typeof SponsorsRoute
  SubscriptionsRoute: typeof SubscriptionsRoute
  UsersRoute: typeof UsersRoute
  VolunteersRoute: typeof VolunteersRoute
  AnalyticsParticipationRoute: typeof AnalyticsParticipationRoute
  AnalyticsRevenueRoute: typeof AnalyticsRevenueRoute
  CertificatesIdRoute: typeof CertificatesIdRoute
  CompetitionsIdRoute: typeof CompetitionsIdRoute
  EventsIdRoute: typeof EventsIdRoute
  EventsNewRoute: typeof EventsNewRoute
  EventsScheduleRoute: typeof EventsScheduleRoute
  SubmissionsIdRoute: typeof SubmissionsIdRoute
  TeamsIdRoute: typeof TeamsIdRoute
  CertificatesIndexRoute: typeof CertificatesIndexRoute
  CompetitionsIndexRoute: typeof CompetitionsIndexRoute
  EventsIndexRoute: typeof EventsIndexRoute
  SubmissionsIndexRoute: typeof SubmissionsIndexRoute
  TeamsIndexRoute: typeof TeamsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-logs': {
      id: '/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluations': {
      id: '/evaluations'
      path: '/evaluations'
      fullPath: '/evaluations'
      preLoaderRoute: typeof EvaluationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/judges': {
      id: '/judges'
      path: '/judges'
      fullPath: '/judges'
      preLoaderRoute: typeof JudgesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentors': {
      id: '/mentors'
      path: '/mentors'
      fullPath: '/mentors'
      preLoaderRoute: typeof MentorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations': {
      id: '/organizations'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof OrganizationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruitment': {
      id: '/recruitment'
      path: '/recruitment'
      fullPath: '/recruitment'
      preLoaderRoute: typeof RecruitmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registrations': {
      id: '/registrations'
      path: '/registrations'
      fullPath: '/registrations'
      preLoaderRoute: typeof RegistrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles': {
      id: '/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof RolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sponsors': {
      id: '/sponsors'
      path: '/sponsors'
      fullPath: '/sponsors'
      preLoaderRoute: typeof SponsorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscriptions': {
      id: '/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof SubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volunteers': {
      id: '/volunteers'
      path: '/volunteers'
      fullPath: '/volunteers'
      preLoaderRoute: typeof VolunteersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/participation': {
      id: '/analytics/participation'
      path: '/analytics/participation'
      fullPath: '/analytics/participation'
      preLoaderRoute: typeof AnalyticsParticipationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/revenue': {
      id: '/analytics/revenue'
      path: '/analytics/revenue'
      fullPath: '/analytics/revenue'
      preLoaderRoute: typeof AnalyticsRevenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificates/': {
      id: '/certificates/'
      path: '/certificates'
      fullPath: '/certificates/'
      preLoaderRoute: typeof CertificatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificates/$id': {
      id: '/certificates/$id'
      path: '/certificates/$id'
      fullPath: '/certificates/$id'
      preLoaderRoute: typeof CertificatesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competitions/': {
      id: '/competitions/'
      path: '/competitions'
      fullPath: '/competitions/'
      preLoaderRoute: typeof CompetitionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competitions/$id': {
      id: '/competitions/$id'
      path: '/competitions/$id'
      fullPath: '/competitions/$id'
      preLoaderRoute: typeof CompetitionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$id': {
      id: '/events/$id'
      path: '/events/$id'
      fullPath: '/events/$id'
      preLoaderRoute: typeof EventsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/new': {
      id: '/events/new'
      path: '/events/new'
      fullPath: '/events/new'
      preLoaderRoute: typeof EventsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/schedule': {
      id: '/events/schedule'
      path: '/events/schedule'
      fullPath: '/events/schedule'
      preLoaderRoute: typeof EventsScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submissions/': {
      id: '/submissions/'
      path: '/submissions'
      fullPath: '/submissions/'
      preLoaderRoute: typeof SubmissionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submissions/$id': {
      id: '/submissions/$id'
      path: '/submissions/$id'
      fullPath: '/submissions/$id'
      preLoaderRoute: typeof SubmissionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/': {
      id: '/teams/'
      path: '/teams'
      fullPath: '/teams/'
      preLoaderRoute: typeof TeamsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$id': {
      id: '/teams/$id'
      path: '/teams/$id'
      fullPath: '/teams/$id'
      preLoaderRoute: typeof TeamsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditLogsRoute: AuditLogsRoute,
  EvaluationsRoute: EvaluationsRoute,
  JudgesRoute: JudgesRoute,
  MentorsRoute: MentorsRoute,
  NotificationsRoute: NotificationsRoute,
  OrganizationsRoute: OrganizationsRoute,
  RecruitmentRoute: RecruitmentRoute,
  RegistrationsRoute: RegistrationsRoute,
  ReportsRoute: ReportsRoute,
  RolesRoute: RolesRoute,
  SettingsRoute: SettingsRoute,
  SponsorsRoute: SponsorsRoute,
  SubscriptionsRoute: SubscriptionsRoute,
  UsersRoute: UsersRoute,
  VolunteersRoute: VolunteersRoute,
  AnalyticsParticipationRoute: AnalyticsParticipationRoute,
  AnalyticsRevenueRoute: AnalyticsRevenueRoute,
  CertificatesIdRoute: CertificatesIdRoute,
  CompetitionsIdRoute: CompetitionsIdRoute,
  EventsIdRoute: EventsIdRoute,
  EventsNewRoute: EventsNewRoute,
  EventsScheduleRoute: EventsScheduleRoute,
  SubmissionsIdRoute: SubmissionsIdRoute,
  TeamsIdRoute: TeamsIdRoute,
  CertificatesIndexRoute: CertificatesIndexRoute,
  CompetitionsIndexRoute: CompetitionsIndexRoute,
  EventsIndexRoute: EventsIndexRoute,
  SubmissionsIndexRoute: SubmissionsIndexRoute,
  TeamsIndexRoute: TeamsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
